server:
  port: 8080

spring:
  application:
    name: h-charity-api
  datasource:
    url: jdbc:mariadb://localhost:3306/hcharity
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 750KB
      max-request-size: 750KB

jwt:
  cookieName: hcharity-jwt
  refreshCookieName: hcharity-jwt-refresh
  secret: 2hJDHDHDHDHGFdeZHimanismCharityApp2024PassKeyDontTryToHackIt
  expiration: 1200000
  refreshExpirationMs: 180000

stripe:
  secret-key: YOUR_STRIPE_SECRET_KEY
